### ISSUE TITLE
The version should be all right, but the following error occurred.

### ISSUE THREAD

**Issue by shilm** [wwwlicious/servicestack-seq-requestlogsfeature#22]
"startUpErrors": [{
		"errorCode": "TypeLoadException",
		"message": "Method 'get_RequestLogFilter' in type 'ServiceStack.Seq.RequestLogsFeature.SeqRequestLogger' from assembly 'ServiceStack.Seq.RequestLogsFeature, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.",
		"stackTrace": "[Object: 11/21/2018 14:34:09]:\n[REQUEST: ]\nSystem.TypeLoadException: Method 'get_RequestLogFilter' in type 'ServiceStack.Seq.RequestLogsFeature.SeqRequestLogger' from assembly 'ServiceStack.Seq.RequestLogsFeature, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.\n   at ServiceStack.Seq.RequestLogsFeature.SeqRequestLogsFeature.get_Logger()\n   at ServiceStack.Seq.RequestLogsFeature.SeqRequestLogsFeature.ConfigureRequestLogger(IAppHost appHost)\n   at ServiceStack.Seq.RequestLogsFeature.SeqRequestLogsFeature.Register(IAppHost appHost)\n   at ServiceStack.ServiceStackHost.LoadPluginsInternal(IPlugin[] plugins)",
		"errors": []
	}],

**Comment by wwwlicious** [comment]
Hard to know what to do with that if I'm honest. 

It looks like an assembly binding redirect issue, I've had similar between mixing netstandard and netfx projects. The implementation of the interface resides within the same assembly so it's not like it isn't there.

Can you create a demo project reproducing the issue? ...otherwise I doubt I can do much here.

**Comment by shilm** [comment]
I changed SS version to 5.1.0
It seems that the problem has been solved
thankyou！
