### ISSUE TITLE
Package will not install

### ISSUE THREAD

**Issue by scpeterson** [wwwlicious/servicestack-seq-requestlogsfeature#7]
I am attempting to install the package via Nuget and am getting the error:

Could not install package 'ServiceStack.Seq.RequestLogsFeature 4.0.57.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What am I missing?

Thanks

**Comment by wwwlicious** [comment]
Thanks for raising the issue. I think the problem you are having is that the package only targets .Net 4.5.2. This is following Microsoft's announcement to deprecate versions 4 - 4.5.1 since Jan 12 of this year so I apologise, but we haven't included support for these versions.

More on the details of the announcement can be found @ https://www.infoq.com/news/2014/08/NET40-EOL

I would recommend if you are able, to upgrade the project to .Net 4.5.2 and the package should then install.

It is probably also worth mentioning that ServiceStack is also planning on deprecating it's own support for these versions on August 1st but there is an issue for continued support open if you want to vote for it.
ServiceStack announcement: https://plus.google.com/+DemisBellot/posts/E98Nh4iGLfi
Uservoice Feature Request: https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/12528912-continue-supporting-net-4-0-projects

**Comment by scpeterson** [comment]
Thanks for the information.  I knew about support for 4.5.1 going away, but didn't know that this project was 4.5.2 only.  I've added a task to our project to upgrade to 4.5.2, which should make this issue go away.
